version: '3'

services:
    mariadb:
        build: /Users/omar/Documents/inception/srcs/requirements/mariadb 
        image: mariadb
        container_name : mariadb
        restart: unless-stopped
        env_file:
            - .env
        networks:
            - wordpress
        volumes:
            - 'db:/var/lib/mysql'
        init: true
    nginx:
        build: /Users/omar/Documents/inception/srcs/requirements/nginx
        depends_on:
            - wordpress
        image: nginx
        container_name : nginx
        restart: unless-stopped
        ports:
            - "443:443"
        networks:
            - wordpress
        volumes:
            - 'wordpress:/var/www/'
            - 'port:/var/www/web'
        init: true
    wordpress:
        build: /Users/omar/Documents/inception/srcs/requirements/wordpress
        image: wordpress
        depends_on:
            - mariadb
        container_name : wordpress
        restart: unless-stopped
        env_file:
            - .env
        networks:
            - wordpress
        volumes:
            - 'wordpress:/var/www/'
        init: true
    redis:
        build: /Users/omar/Documents/inception/srcs/requirements/bonus/redis-cach
        image: redis
        depends_on:
            - wordpress
        container_name: redis
        restart: unless-stopped
        env_file:
            - .env
        networks:
            - wordpress
        volumes:
            - 'redis:/var/lib/redis'
        init: true
    adminer:
        build: /Users/omar/Documents/inception/srcs/requirements/bonus/adminer
        image: adminer
        depends_on:
            - wordpress
        container_name: adminer
        restart: unless-stopped
        networks:
            - wordpress
        environment:
            AMDINER_DEFAULT_SERVER: mariadb
        volumes:
            - 'wordpress:/var/www/'
        init: true
    ftp:
        build: /Users/omar/Documents/inception/srcs/requirements/bonus/ftp
        image: ftp
        container_name : ftp
        restart: unless-stopped
        ports:
            - "21:21"
            - "21000-21010:21000-21010"
        env_file:
            - .env
        networks:
            - wordpress
        volumes:
            - 'wordpress:/home/oel-berh/wordpress'
        init: true
    portainer:
        build: /Users/omar/Documents/inception/srcs/requirements/bonus/portainer
        image: portainer
        container_name : portainer
        restart: unless-stopped
        networks:
            - wordpress
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - 'data:/data/'
        init: true
    port:
        build: /Users/omar/Documents/inception/srcs/requirements/bonus/port
        image: port
        container_name : port
        networks:
            - wordpress
        volumes:
            - 'port:/var/www/web'
networks:
  wordpress:
    driver: bridge
volumes:
    wordpress:
        # driver: "local"
        # driver_opts:
            # o: bind
            # type: ext4
            # device: /home/oel-berh/data/wp
    db:
        # driver: "local"
        # driver_opts:
            # o: bind
            # type: ext4
            # device: /home/oel-berh/data/db
    redis:
    data:
    port: