FROM debian:buster
RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install mariadb-server mariadb-client -y
RUN sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf
# EXPOSE 3306
COPY h.sh .
COPY db.sql .
ENTRYPOINT ["sh", "h.sh"]
CMD [ "mysqld" ]
