FROM debian:buster
RUN apt-get -y update && apt-get install -y wget php php-mysql adminer
COPY ./tools/adminer.sh /
RUN chmod +x /adminer.sh
WORKDIR /var/www/html/wordpress/
ENTRYPOINT ["sh", "/adminer.sh"]

