FROM debian:buster
RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install wget sudo php7.3-fpm php7.3-mysql mariadb-client -y

WORKDIR /var/www/html
RUN wget https://wordpress.org/latest.tar.gz
RUN tar xvf latest.tar.gz
RUN rm latest.tar.gz

RUN sed -i 's|listen = /run/php/php7.3-fpm.sock|listen = 0.0.0.0:9000|g' /etc/php/7.3/fpm/pool.d/www.conf

RUN chown -R www-data:www-data /var/www/
RUN mkdir /run/php/

RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN sudo mv wp-cli.phar /usr/local/bin/wp && chmod 777 /usr/local/bin/wp
RUN wp core download --allow-root
COPY /wordpress.sh /var/www/html/wordpress/
WORKDIR /var/www/html/wordpress/
RUN chmod 777  wordpress.sh

ENTRYPOINT sh wordpress.sh
# CMD ["php-fpm7.3", "-F", "-R"]
