FROM debian:buster
RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install nginx openssl -y 
COPY ./conf/nginx.crt /etc/ssl/certs/nginx.crt
COPY ./conf/nginx.key /etc/ssl/private/nginx.key
COPY ./conf/default /etc/nginx/sites-available/

ENTRYPOINT nginx -g 'daemon off;'
