FROM debian:buster
RUN apt-get -y update && apt-get -y upgrade
RUN apt-get install -y nginx openssl
COPY ./tools/nginx.crt /etc/ssl/certs/nginx.crt
COPY ./tools/nginx.key /etc/ssl/private/nginx.key
COPY ./tools/default /etc/nginx/sites-available/default
RUN chmod 777 /etc/nginx/sites-available/default

ENTRYPOINT nginx -g 'daemon off;'
