FROM debian:buster
RUN apt-get update && apt-get install -y vsftpd
COPY vsftpd.conf /etc/vsftpd.conf
COPY ftp.sh .
EXPOSE 21
CMD [ "sh", "ftp.sh"]
# ENTRYPOINT sh ftp.sh
# CMD ["/usr/sbin/vsftpd", "/etc/vsftpd.conf"]
# ENTRYPOINT ["/usr/sbin/vsftpd", "/etc/vsftpd/vsftpd.conf"]
# ENTRYPOINT ["/usr/sbin/vsftpd", "/etc/vsftpd/vsftpd.conf"]

